[tool.poetry]
name = "kadet"
version = "0.2.0"
description = "Easily define and reuse complex Python objects that serialize into JSON or YAML."
authors = ["Ricardo Amaro <ramaro@kapicorp.com>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = '>=3.7'
PyYAML = ">=5.3.1"
typeguard = ">=2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
